const REQUEST_COMICS = 'REQUEST_COMICS';
const RECEIVE_COMICS = 'RECEIVED_COMICS';
const REQUEST_CHARACTERS = 'request_characters'
const RECEIVE_CHARACTERS = 'receive_comics'
export default {
    REQUEST_CHARACTERS, 
    RECEIVE_CHARACTERS,
    RECEIVE_COMICS, 
    REQUEST_COMICS
}
